version: '3.8'

services:
  app:
    build:
      container_name: comments_backend
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - /.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge